//******************************************************************
// 
//  Generated by RoboCompDSL
//  
//  File name: ASRPublish.ice
//  Source: ASRPublish.idsl
//
//******************************************************************
#ifndef ROBOCOMPASRPUBLISH_ICE
#define ROBOCOMPASRPUBLISH_ICE
module RoboCompASRPublish
{
	interface ASRPublish
	{
		void newText (string text);
	};
};

#endif
