# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainUI.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import gui_rc

class Ui_guiDlg(object):
    def setupUi(self, guiDlg):
        if not guiDlg.objectName():
            guiDlg.setObjectName(u"guiDlg")
        guiDlg.resize(1402, 720)
        self.drop_shadow_layout = QHBoxLayout(guiDlg)
        self.drop_shadow_layout.setSpacing(0)
        self.drop_shadow_layout.setObjectName(u"drop_shadow_layout")
        self.drop_shadow_layout.setContentsMargins(10, 10, 10, 10)
        self.drop_shadow_frame = QFrame(guiDlg)
        self.drop_shadow_frame.setObjectName(u"drop_shadow_frame")
        self.drop_shadow_frame.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.884, y2:1, stop:0 rgba(0, 119, 179, 255), stop:1 rgba(25, 70, 153, 255));\n"
"border-radius:10px;\n"
"\n"
"")
        self.drop_shadow_frame.setFrameShape(QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.title = QFrame(self.drop_shadow_frame)
        self.title.setObjectName(u"title")
        self.title.setMaximumSize(QSize(16777215, 50))
        self.title.setStyleSheet(u"background-color:none;")
        self.title.setFrameShape(QFrame.StyledPanel)
        self.title.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.title)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 1221, 31))
        font = QFont()
        font.setFamily(u"Noto Color Emoji")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color:rgb(236,236,236)")
        self.label.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.title)

        self.frame_3 = QFrame(self.drop_shadow_frame)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setStyleSheet(u"background-color:none;")
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.textoaenviar = QLineEdit(self.frame_3)
        self.textoaenviar.setObjectName(u"textoaenviar")
        self.textoaenviar.setGeometry(QRect(60, 60, 331, 71))
        self.textoaenviar.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(192, 192, 192, 255), stop:1 rgba(225, 225, 225, 255));")
        self.asignarnombre = QPushButton(self.frame_3)
        self.asignarnombre.setObjectName(u"asignarnombre")
        self.asignarnombre.setGeometry(QRect(930, 100, 171, 31))
        self.asignarnombre.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(192, 192, 192, 255), stop:1 rgba(225, 225, 225, 255));")
        self.muestramensajes = QPlainTextEdit(self.frame_3)
        self.muestramensajes.setObjectName(u"muestramensajes")
        self.muestramensajes.setGeometry(QRect(450, 20, 351, 91))
        self.muestramensajes.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(192, 192, 192, 255), stop:1 rgba(225, 225, 225, 255));")
        self.comportamientoaleatorio = QCheckBox(self.frame_3)
        self.comportamientoaleatorio.setObjectName(u"comportamientoaleatorio")
        self.comportamientoaleatorio.setGeometry(QRect(890, 530, 16, 21))
        self.comportamientoaleatorio.setStyleSheet(u"")
        self.label_2 = QLabel(self.frame_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(959, 40, 131, 16))
        self.label_2.setStyleSheet(u"color: rgb(227, 227, 227);")
        self.label_6 = QLabel(self.frame_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(160, 340, 141, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.label_6.setFont(font1)
        self.label_6.setStyleSheet(u"color: rgb(227, 227, 227);")
        self.mandarfrase = QPushButton(self.frame_3)
        self.mandarfrase.setObjectName(u"mandarfrase")
        self.mandarfrase.setGeometry(QRect(150, 230, 171, 41))
        self.mandarfrase.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(192, 192, 192, 255), stop:1 rgba(225, 225, 225, 255));")
        self.respuesta = QPlainTextEdit(self.frame_3)
        self.respuesta.setObjectName(u"respuesta")
        self.respuesta.setGeometry(QRect(60, 380, 331, 71))
        self.respuesta.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(192, 192, 192, 255), stop:1 rgba(225, 225, 225, 255));")
        self.respuesta.setFrameShape(QFrame.Panel)
        self.respuesta.setFrameShadow(QFrame.Sunken)
        self.si = QPushButton(self.frame_3)
        self.si.setObjectName(u"si")
        self.si.setGeometry(QRect(930, 440, 80, 41))
        self.si.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(192, 192, 192, 255), stop:1 rgba(225, 225, 225, 255));")
        self.label_3 = QLabel(self.frame_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(160, 470, 141, 31))
        self.label_3.setFont(font1)
        self.label_3.setStyleSheet(u"color: rgb(227, 227, 227);")
        self.limpiarconversacion = QPushButton(self.frame_3)
        self.limpiarconversacion.setObjectName(u"limpiarconversacion")
        self.limpiarconversacion.setGeometry(QRect(560, 560, 151, 21))
        self.limpiarconversacion.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(192, 192, 192, 255), stop:1 rgba(225, 225, 225, 255));")
        self.nombreaintroducir = QLineEdit(self.frame_3)
        self.nombreaintroducir.setObjectName(u"nombreaintroducir")
        self.nombreaintroducir.setGeometry(QRect(930, 60, 171, 21))
        self.nombreaintroducir.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(192, 192, 192, 255), stop:1 rgba(225, 225, 225, 255));")
        self.grabar_2 = QCheckBox(self.frame_3)
        self.grabar_2.setObjectName(u"grabar_2")
        self.grabar_2.setGeometry(QRect(290, 320, 16, 21))
        self.textoescuchado = QLineEdit(self.frame_3)
        self.textoescuchado.setObjectName(u"textoescuchado")
        self.textoescuchado.setGeometry(QRect(60, 510, 331, 71))
        self.textoescuchado.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(192, 192, 192, 255), stop:1 rgba(225, 225, 225, 255));")
        self.no = QPushButton(self.frame_3)
        self.no.setObjectName(u"no")
        self.no.setGeometry(QRect(1020, 440, 80, 41))
        self.no.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(192, 192, 192, 255), stop:1 rgba(225, 225, 225, 255));")
        self.frasesPredefinidas = QComboBox(self.frame_3)
        self.frasesPredefinidas.addItem("")
        self.frasesPredefinidas.addItem("")
        self.frasesPredefinidas.addItem("")
        self.frasesPredefinidas.setObjectName(u"frasesPredefinidas")
        self.frasesPredefinidas.setGeometry(QRect(60, 150, 331, 23))
        self.exportarpdf = QPushButton(self.frame_3)
        self.exportarpdf.setObjectName(u"exportarpdf")
        self.exportarpdf.setGeometry(QRect(560, 530, 151, 21))
        self.exportarpdf.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(192, 192, 192, 255), stop:1 rgba(225, 225, 225, 255));")
        self.tipofrases = QComboBox(self.frame_3)
        self.tipofrases.addItem("")
        self.tipofrases.addItem("")
        self.tipofrases.addItem("")
        self.tipofrases.setObjectName(u"tipofrases")
        self.tipofrases.setGeometry(QRect(60, 190, 331, 23))
        self.botonneutral = QPushButton(self.frame_3)
        self.botonneutral.setObjectName(u"botonneutral")
        self.botonneutral.setGeometry(QRect(1100, 270, 81, 31))
        font2 = QFont()
        font2.setFamily(u"Noto Color Emoji")
        self.botonneutral.setFont(font2)
        self.botonneutral.setStyleSheet(u"QPushButton {\n"
"	border: none;\n"
"	border-radius: 7px;\n"
"	background-color: rgb(255, 230, 85);\n"
"}\n"
"QPushButton:hover{\n"
"	background-color: rgba(85,255,127,150);\n"
"}")
        self.label_7 = QLabel(self.frame_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(180, 20, 91, 31))
        font3 = QFont()
        font3.setFamily(u"Noto Color Emoji")
        font3.setPointSize(18)
        self.label_7.setFont(font3)
        self.label_7.setStyleSheet(u"color: rgb(227, 227, 227);")
        self.botondisgustado = QPushButton(self.frame_3)
        self.botondisgustado.setObjectName(u"botondisgustado")
        self.botondisgustado.setGeometry(QRect(850, 270, 80, 31))
        self.botondisgustado.setStyleSheet(u"background-color: rgb(255, 230, 85);")
        self.botonalegria = QPushButton(self.frame_3)
        self.botonalegria.setObjectName(u"botonalegria")
        self.botonalegria.setGeometry(QRect(910, 210, 80, 31))
        self.botonalegria.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.916, y2:0.994318, stop:0 rgba(121, 239, 0, 255), stop:0.947368 rgba(72, 202, 33, 255));")
        self.botontristeza = QPushButton(self.frame_3)
        self.botontristeza.setObjectName(u"botontristeza")
        self.botontristeza.setGeometry(QRect(850, 340, 81, 31))
        self.botontristeza.setStyleSheet(u"background-color: rgb(223, 47, 16);")
        self.botonenfadado = QPushButton(self.frame_3)
        self.botonenfadado.setObjectName(u"botonenfadado")
        self.botonenfadado.setGeometry(QRect(970, 390, 91, 31))
        self.botonenfadado.setStyleSheet(u"background-color: rgb(223, 47, 16);")
        self.botonmiedo = QPushButton(self.frame_3)
        self.botonmiedo.setObjectName(u"botonmiedo")
        self.botonmiedo.setGeometry(QRect(1100, 340, 80, 31))
        self.botonmiedo.setStyleSheet(u"background-color: rgb(223, 47, 16);")
        self.botonsorpresa = QPushButton(self.frame_3)
        self.botonsorpresa.setObjectName(u"botonsorpresa")
        self.botonsorpresa.setGeometry(QRect(1030, 210, 80, 31))
        self.botonsorpresa.setStyleSheet(u"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.916, y2:0.994318, stop:0 rgba(121, 239, 0, 255), stop:0.947368 rgba(72, 202, 33, 255));")
        self.label_8 = QLabel(self.frame_3)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(950, 300, 131, 31))
        self.label_8.setFont(font3)
        self.label_8.setStyleSheet(u"color: rgb(227, 227, 227);")
        self.label_4 = QLabel(self.frame_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(910, 530, 221, 21))
        self.label_4.setFont(font1)
        self.label_4.setStyleSheet(u"color: rgb(227, 227, 227);")
        self.label_5 = QLabel(self.frame_3)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(310, 320, 111, 21))
        self.label_5.setFont(font1)
        self.label_5.setStyleSheet(u"color: rgb(227, 227, 227);")
        self.label_9 = QLabel(self.frame_3)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(480, 480, 331, 31))
        self.label_9.setFont(font3)
        self.label_9.setStyleSheet(u"color: rgb(227, 227, 227);")
        self.label_10 = QLabel(self.frame_3)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(180, 310, 91, 31))
        self.label_10.setFont(font3)
        self.label_10.setStyleSheet(u"color: rgb(227, 227, 227);")
        self.textEdit = QTextEdit(self.frame_3)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(500, 150, 251, 251))
        self.textEdit.setStyleSheet(u"border-image: url(:/newPrefix/ebo.png);")
        self.textoaenviar.raise_()
        self.asignarnombre.raise_()
        self.muestramensajes.raise_()
        self.comportamientoaleatorio.raise_()
        self.label_2.raise_()
        self.label_6.raise_()
        self.mandarfrase.raise_()
        self.respuesta.raise_()
        self.si.raise_()
        self.label_3.raise_()
        self.limpiarconversacion.raise_()
        self.nombreaintroducir.raise_()
        self.grabar_2.raise_()
        self.textoescuchado.raise_()
        self.no.raise_()
        self.frasesPredefinidas.raise_()
        self.exportarpdf.raise_()
        self.tipofrases.raise_()
        self.label_7.raise_()
        self.botonneutral.raise_()
        self.botondisgustado.raise_()
        self.botonalegria.raise_()
        self.botontristeza.raise_()
        self.botonenfadado.raise_()
        self.botonmiedo.raise_()
        self.botonsorpresa.raise_()
        self.label_8.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.textEdit.raise_()

        self.verticalLayout.addWidget(self.frame_3)


        self.drop_shadow_layout.addWidget(self.drop_shadow_frame)


        self.retranslateUi(guiDlg)

        QMetaObject.connectSlotsByName(guiDlg)
    # setupUi

    def retranslateUi(self, guiDlg):
        guiDlg.setWindowTitle(QCoreApplication.translate("guiDlg", u"interactGUI", None))
        self.label.setText(QCoreApplication.translate("guiDlg", u"EBO Controller", None))
        self.asignarnombre.setText(QCoreApplication.translate("guiDlg", u"Asignar nombre", None))
        self.comportamientoaleatorio.setText("")
        self.label_2.setText(QCoreApplication.translate("guiDlg", u"Nombre del usuario", None))
        self.label_6.setText(QCoreApplication.translate("guiDlg", u"Texto reconocido", None))
        self.mandarfrase.setText(QCoreApplication.translate("guiDlg", u"Enviar", None))
        self.si.setText(QCoreApplication.translate("guiDlg", u"Si", None))
        self.label_3.setText(QCoreApplication.translate("guiDlg", u"Texto escuchado", None))
        self.limpiarconversacion.setText(QCoreApplication.translate("guiDlg", u"Limpiar conversaci\u00f3n", None))
        self.grabar_2.setText("")
        self.no.setText(QCoreApplication.translate("guiDlg", u"No", None))
        self.frasesPredefinidas.setItemText(0, QCoreApplication.translate("guiDlg", u"Buenos d\u00edas \u00bfQu\u00e9 tal est\u00e1s?", None))
        self.frasesPredefinidas.setItemText(1, QCoreApplication.translate("guiDlg", u"\u00bfC\u00f3mo te llamas?", None))
        self.frasesPredefinidas.setItemText(2, QCoreApplication.translate("guiDlg", u"Me alegra que est\u00e9s bien", None))

        self.exportarpdf.setText(QCoreApplication.translate("guiDlg", u"Exportar a PDF", None))
        self.tipofrases.setItemText(0, QCoreApplication.translate("guiDlg", u"Buenos d\u00edas \u00bfQu\u00e9 tal est\u00e1s?", None))
        self.tipofrases.setItemText(1, QCoreApplication.translate("guiDlg", u"\u00bfC\u00f3mo te llamas?", None))
        self.tipofrases.setItemText(2, QCoreApplication.translate("guiDlg", u"Me alegra que est\u00e9s bien", None))

        self.botonneutral.setText(QCoreApplication.translate("guiDlg", u"Neutral", None))
        self.label_7.setText(QCoreApplication.translate("guiDlg", u"Hablar", None))
        self.botondisgustado.setText(QCoreApplication.translate("guiDlg", u"Disgustado", None))
        self.botonalegria.setText(QCoreApplication.translate("guiDlg", u"Alegr\u00eda", None))
        self.botontristeza.setText(QCoreApplication.translate("guiDlg", u"Tristeza", None))
        self.botonenfadado.setText(QCoreApplication.translate("guiDlg", u"Enfadado", None))
        self.botonmiedo.setText(QCoreApplication.translate("guiDlg", u"Miedo", None))
        self.botonsorpresa.setText(QCoreApplication.translate("guiDlg", u"Sorpresa", None))
        self.label_8.setText(QCoreApplication.translate("guiDlg", u"Emociones", None))
        self.label_4.setText(QCoreApplication.translate("guiDlg", u"Funcionamiento aut\u00f3nomo", None))
        self.label_5.setText(QCoreApplication.translate("guiDlg", u"Grabar audio", None))
        self.label_9.setText(QCoreApplication.translate("guiDlg", u"Almacenar conversaci\u00f3n", None))
        self.label_10.setText(QCoreApplication.translate("guiDlg", u"Grabar", None))
    # retranslateUi

